Version 0.8-0017

diff --git a/src/scripts/common b/src/scripts/common
--- a/src/scripts/common
+++ b/src/scripts/common
@@ -81,25 +81,25 @@ start() {
 ##		echo "Add 99robocopy.hotplug" 1>>$LOGFILE
 ##		ln -s $PRIVATE_LOCATION/bin/hotplug.sh /usr/syno/hotplug.d/default/99robocopy.hotplug
 ##	fi
-	# Validate 
-	HAS_ERROR=0
-	for file in $SRC_FILES
-	do
-		VALID_RESULT=`perl -I"${PRIVATE_LOCATION}/lib" -c "${PRIVATE_LOCATION}/${file}" 2>&1`
-		if [ "$?"  -ne 0 ]
-		then
-			HAS_ERROR=1
-			echo "   File '${file##*/}' - invalid" 1>>$LOGFILE
-#			echo "-------------------------------" 1>>$LOGFILE
-#			echo "${VALID_RESULT}" 1>>$LOGFILE
-#			echo "-------------------------------" 1>>$LOGFILE
-#		else
-#			echo "   File '${file##*/}' - valid" 1>>$LOGFILE
-		fi
-	done
-	if [ "$HAS_ERROR"  -ne 0 ]; then
-		exit 1
-	fi
+#	# Validate 
+#	HAS_ERROR=0
+#	for file in $SRC_FILES
+#	do
+#		VALID_RESULT=`perl -I"${PRIVATE_LOCATION}/lib" -c "${PRIVATE_LOCATION}/${file}" 2>&1`
+#		if [ "$?"  -ne 0 ]
+#		then
+#			HAS_ERROR=1
+#			echo "   File '${file##*/}' - invalid" 1>>$LOGFILE
+##			echo "-------------------------------" 1>>$LOGFILE
+##			echo "${VALID_RESULT}" 1>>$LOGFILE
+##			echo "-------------------------------" 1>>$LOGFILE
+##		else
+##			echo "   File '${file##*/}' - valid" 1>>$LOGFILE
+#		fi
+#	done
+#	if [ "$HAS_ERROR"  -ne 0 ]; then
+#		exit 1
+#	fi
 
 
 	if [ "$SYNOPKG_DSM_VERSION_MAJOR" == "4" ]; then
